[build]
  command = "npm run build"
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch"]

[[redirects]]
from = "/sitemap.xml"
to = "/sitemap.xml"
status = 200
force = true